name: 'mar2_homo_g'
params:
  global_missing: True
  mf_strategy: "all"
  mr_dist: "uniform_int"
  mr_lower: 0.3
  mr_upper: 0.7
  mm_mech: "mar_sigmoid"
  mm_strictness: True
  mm_obs: True
  mm_feature_option: 'allk=0.2'
  mm_beta_option: 'fixed'
  mm_funcs_bank: 'lr'