name: 'mnar2-heter'
params:
  global_missing: False
  mf_strategy: "all"
  mr_dist: "uniform_int"
  mr_lower: 0.3
  mr_upper: 0.7
  mm_mech: "mnar_sigmoid"
  mm_strictness: True
  mm_feature_option: 'allk=0.1'
  mm_beta_option: 'self'
  mm_funcs_dist: 'random2'
  mm_funcs_bank: 'lr'