defaults:
  - /imp_workflow@_group_: em

imp_name: 'em'
imp_params:
  clip: false
  use_y: false
model_train_params:
  max_iterations: 400
  convergence_thres: 0.001
  local_epoch: 1
  evaluation_interval: 1
  save_model_interval: 10
