defaults:
  - /imp_workflow@_group_: jm

imp_name: gain
imp_params:
  clip: true
  imp_model_params:
    h_dim: 64
    n_layers: 2
    activation: 'relu'
    loss_alpha: 50
    hint_rate: 0.3
model_train_params:
  initial_zero_impute: true
  global_epoch: 200
  local_epoch: 5
  batch_size: 256
  learning_rate: 0.001
  weight_decay: 0.0001
  scheduler: "step"
  scheduler_params:
    step_size: 10
    gamma: 0.5
    schedule_last_epoch: -1
  optimizer: 'adam'
  use_early_stopping: true
  model_converge:
    tolerance: 0.01
    patience: 10
    window_size: 4
    check_steps: 1
    back_steps: 20
  log_interval: 100
  imp_interval: 100