defaults:
  - /imp_workflow@_group_: ice_grad

# configuration for linear ice imputation
imp_name: 'linear_sgd_ice'
imp_params:
  estimator_num: 'ridge'
  estimator_cat: 'logit'
  mm_model: 'logistic'
  mm_model_params:
    class_weight: 'balanced'
    Cs: [1e-1]
    cv: 3
  imp_model_params:
    hidden_dim_min: 16
    hidden_dim_max: 64
    hidden_dim_factor: 2
  clip: True
  use_y: False
model_train_params:
  global_epoch: 1
  local_epoch: 100
  batch_size: 1
  learning_rate: 0.1
  weight_decay: 0.000
  model_converge_tol: 0.001
  model_converge_patience: 10
  use_early_stopping: true
  scheduler: 'step'
  scheduler_params:
    step_size: 10
    gamma: 0.5
    last_epoch: -1
  optimizer: 'adam'
  log_interval: 1