defaults:
  - /imp_workflow@_group_: ice

imp_name: 'linear_ice'
imp_params:
  estimator_num: 'ridge_cv'
  estimator_cat: 'logistic_cv'
  mm_model: 'logistic'
  mm_model_params:
    class_weight: 'balanced'
    Cs: [1e-1]
    cv: 3
  clip: True
  use_y: False
model_train_params:
  early_stopping: True
  tolerance: 0.001
  tolerance_patience: 5
  increase_patience: 5
  window_size: 3
  log_interval: 1
  save_model_interval: 2