defaults:
  - /imp_workflow@_group_: ice

imp_name: 'missforest'
imp_params:
  imp_model_params:
    n_estimators: 200
    bootstrap: True
    n_jobs: 2
  clip: True
  use_y: False
model_train_params:
  early_stopping: True
  tolerance: 0.001
  tolerance_patience: 5
  increase_patience: 5
  window_size: 3
  log_interval: 1
  save_model_interval: 5