defaults:
  - /imp_workflow@_group_: ice

imp_name: 'missforest'
imp_params:
  imp_model_params:
    n_estimators: 100
    bootstrap: True
    n_jobs: -1
  clip: True
  use_y: False
model_train_params: {}