defaults:
  - /imp_workflow@_group_: jm

imp_name: miwae
imp_params:
  clip: true
  imp_model_params:
    latent_size: 4
    n_hidden: 16
    n_hidden_layers: 2
    out_dist: 'gaussian'
    K: 20
    L: 500
    activation: 'tanh'
    initializer: 'xavier'
model_train_params:
  initial_zero_impute: true
  global_epoch: 300
  local_epoch: 5
  batch_size: 512
  learning_rate: 0.001
  weight_decay: 0.0001
  scheduler: "step"
  scheduler_params:
    step_size: 10
    gamma: 0.5
    schedule_last_epoch: -1
  optimizer: 'adam'
  use_early_stopping: true
  early_stopping_mode: 'local'
  model_converge:
    tolerance: 0.003
    tolerance_patience: 20
    increase_patience: 20
    window_size: 20
    check_steps: 1
    back_steps: 1
  log_interval: 20
  imp_interval: 1000
  save_model_interval: 30