defaults:
  - /client@_group_: jm
  - /server@_group_: jm

imp_name: miwae
imp_params:
  imp_model_params:
    latent_size: 16
    n_hidden: 128
    K: 20
    L: 1000
  imp_params:
    local_epochs: 100     # TODO: move to aggregator
    lr: 1e-3              # TODO: move to aggregator
    batch_size: 128
    weight_decay: 0.001   # TODO: move to aggregator
    imp_interval: 100     # TODO: move to aggregator
    verbose: 10
    optimizer: adam       # TODO: move to aggregator