defaults:
  - /imp_workflow@_group_: jm

imp_name: miwae
imp_params:
  clip: false
  imp_model_params:
    latent_size: 16
    n_hidden: 32
    n_hidden_layers: 2
    out_dist: 'gaussian'
    K: 20
    L: 100
model_train_params:
  global_epoch: 200
  local_epoch: 5
  batch_size: 512
  learning_rate: 0.001
  weight_decay: 0.0001
  scheduler: "step"
  scheduler_params:
    step_size: 10
    gamma: 0.5
    schedule_last_epoch: -1
  optimizer: 'adam'
  use_early_stopping: true
  model_converge:
    tolerance: 0.01
    patience: 10
    window_size: 4
    check_steps: 1
    back_steps: 10
  log_interval: 1000