#defaults:
#  - /imp_workflow@_group_: vae

imp_name: miwae
imp_params:
  imp_model_params:
    latent_size: 16
    n_hidden: 64
    K: 20
    L: 100
model_train_params:
  global_epoch: 100
  model_converge_tol: 0.0001
  model_converge_patience: 10
  local_epoch: 5
  batch_size: 512
  lr: 0.001
  weight_decay: 0.0001
  optimizer: 'adam'
  log_interval: 1