defaults:
  - /imp_workflow@_group_: ice_grad

# configuration for linear ice imputation
imp_name: 'mlp_ice'
imp_params:
  estimator_num: 'nn_reg'
  estimator_cat: 'nn_clf'
  mm_model: 'logistic'
  mm_model_params:
    class_weight: 'balanced'
    Cs: [1e-1]
    cv: 3
  imp_model_params:
    hidden_dim_min: 16
    hidden_dim_max: 64
    hidden_dim_factor: 2
  clip: True
  use_y: False
model_train_params:
  global_epoch: 1
  model_converge_tol: 0.001
  model_converge_patience: 200
  local_epoch: 5000
  batch_size: 256
  learning_rate: 0.001
  weight_decay: 0.01
  schedule_step_size: 50
  schedule_gamma: 0.5
  schedule_last_epoch: -1
  optimizer: 'adam'
  log_interval: 1