defaults:
  - /imp_workflow@_group_: jm

imp_name: miwae
imp_params:
  clip: false
  imp_model_params:
    latent_size: 16
    n_hidden: 32
    n_hidden_layers: 2
    out_dist: 'gaussian'
    K: 20
    L: 100
    activation: 'tanh',
    initializer: 'xavier'
    mask_net_type: 'linear'
model_train_params:
  initial_zero_impute: true
  global_epoch: 300
  local_epoch: 5
  batch_size: 256
  learning_rate: 0.001
  weight_decay: 0.0001
  scheduler: "step"
  scheduler_params:
    step_size: 10
    gamma: 0.5
    schedule_last_epoch: -1
  optimizer: 'adam'
  use_early_stopping: true
  early_stopping_mode: 'local'
  model_converge:
    tolerance: 0.005
    tolerance_patience: 20
    increase_patience: 20
    window_size: 20
    check_steps: 1
    back_steps: 1
  log_interval: 1000