defaults:
  - _self_
  - override hydra/launcher: joblib

hydra:
  launcher:
    n_jobs: 8
    verbose: 51
    pre_dispatch: n_jobs

#########################################################
# Configuration Content
scenario_version: 'alpha'
experiment_name: "fed_imp_pc2"
eval_dir_name: 'eval_results'

# Scenario params
dataset_name: "dvisits"
data_partition_name: "niid-t2"
missing_scenario_name: "mar-heter"
imputer_name: "simple"
fed_strategy_name: "local"
round_idx: 7
fed: True

# Evaluation params
eval_params:
  model_params: {}
  train_params: {
    'global_epoch': 100,
    'local_epoch': 10,
    'fine_tune_epoch': 200,
    'tol': 0.0001,
    'patience': 10
  }
  seed: 2180279

log_to_file: False
log_level: "INFO"