defaults:
  - _self_
  - override hydra/launcher: joblib

hydra:
  launcher:
    n_jobs: 8
    verbose: 51
    pre_dispatch: n_jobs

#########################################################
# Configuration Content
scenario_version: 'alpha'
experiment_name: "fed_imp_pc2"
eval_dir_name: 'eval_results'

# Scenario params
dataset_name: "dvisits"
data_partition_name: "niid-t2"
missing_scenario_name: "mnar2-heter"
imputer_name: "miwae"
fed_strategy_name: "local"
round_idx: 4
fed: False

# Evaluation params
eval_params:
  imp_quality_metrics: ['rmse', 'sliced-ws']
  imp_fairness_metrics: ['variance', 'jain-index']
  downstream: True
  model: "nn"
  model_params: {
    'optimizer': 'adam',
    'weight_decay': 0.0,
  }
  seed: 2180279

log_to_file: False
log_level: "INFO"