defaults:
  - _self_
  - imputer: linear_ice
  - agg_strategy: local

########################################################################################################################
# Experiment Meta
debug: false
experiment:
  # name of prefix of experiments e.g. fed_imp, fed_pred etc.
  experiment_name: fed_imp_pc2
  # configuration of output path to save the results
  output_path: ${data.dataset_name}/${data_partition}/${missing_simulate}/${imputer.imp_name}/${agg_strategy.agg_strategy_name}
  # Other Options
  seed: 2180279
  num_rounds: 1
  mtp: False

########################################################################################################################
# Experiment Configuration Content
# dataset
data:
  dataset_name: codon
  test_size: 0.1
# scenarios
num_clients: 2
data_partition: iid-even2
missing_simulate: fixed2@mr=0.5-mm=mnar_quantile-mfunc=lr-k=0.5

# imputer, agg_strategy, imp_workflow
imputer: null
agg_strategy: null
imp_workflow: null

# client, server, evaluator, tracker, result analyzer
client: { }  # todo
server: { }  # todo
evaluator_params: { } # todo
tracker_params:
  track_data: False
  track_model_params: True
  track_misc: True
  persist: 'final'
ret_analyze_params: null