defaults:
  - _self_
  - imputer: miwae
  - fed_strategy: local
  - tracker: none
  - override hydra/launcher: joblib

hydra:
  launcher:
    n_jobs: 8
    verbose: 51
    pre_dispatch: n_jobs

########################################################################################################################
# Experiment Meta
debug: false
experiment:
  # name of prefix of experiments e.g., fed_imp, fed_pred etc.
  experiment_name: fed_imp_pc2
  # configuration of an output path to save the results
  output_path: ${scenario_version}/${dataset_name}/${data_partition_name}_${missing_scenario_name}/${imputer.imp_name}/${fed_strategy.fed_strategy_name}/${round_id}
  # Other Options
  seed: 2180279
  n_rounds: 1
  mtp: False
  log_to_file: False
  logging_level: DEBUG

########################################################################################################################
# Experiment Configuration Content
# scenarios
scenario_version: "alpha"
dataset_name: "hhip"
data_partition_name: "iid-even"
missing_scenario_name: "mcar"
round_id: 0
client_config: {}
server_config: {}  # todo
evaluator_params: {} # todo
imp_workflow: null
ret_analyze_params: null