defaults:
  - _self_
  - imputer: miwae
  - fed_strategy: fedavg
  - tracker: none
  - override hydra/launcher: joblib

hydra:
  launcher:
    n_jobs: -1
    verbose: 40

########################################################################################################################
# Experiment Meta
debug: false
experiment:
  # name of prefix of experiments e.g., fed_imp, fed_pred etc.
  experiment_name: fed_imp_pc2
  # configuration of an output path to save the results
  output_path: ${scenario_version}/${dataset_name}/${data_partition}-${missing_scenario}/${imputer.imp_name}/${fed_strategy.fed_strategy_name}
  # Other Options
  seed: 2180279
  n_rounds: 1
  mtp: False

########################################################################################################################
# Experiment Configuration Content
# scenarios
scenario_version: "alpha"
dataset_name: "codrna"
data_partition_name: "niid-f2"
missing_scenario_name: "mar-homog"
round_id: 0
client_config: {}
server_config: {}  # todo
evaluator_params: {} # todo
imp_workflow: null
ret_analyze_params: null