defaults:
  - _self_
  - data_partition: niid-f1
  - missing_scenario: mar-homog

#########################################################
# Scenario Configuration Content
scenario_version: 'alpha'
dataset_name: hhip
num_clients: 10
seed: 2180279
n_rounds: 10
scenario_name: ${data_partition.name}_${missing_scenario.name}