defaults:
  - _self_
  - override hydra/launcher: submitit_slurm

hydra:
  launcher:
    gres: gpu:1
    nodes: 1
    cpus_per_task: 1
    gpus_per_node: 1
    tasks_per_node: 16
    mem_gb: 2
    timeout_min: 1
    name: test
    partition: p_jsvaidya_1
    array_parallelism: 20
    stderr_to_stdout: True
    setup:
      - source /projects/community/miniconda3/bin/activate impute4fair
      - export CUBLAS_WORKSPACE_CONFIG=:4096:8

seed: 2180279
