name: 'iidsd'
partition_params:
  partition_strategy: "iid"
  split_col: 'target'
  size_strategy: "even"
  sample_iid_direct: True
  min_samples: 100
  max_samples: 2000
  local_test_size: 0.1
  global_test_size: 0.1