name: 'natural-partition'
partition_params:
  partition_strategy: "natural_partition"
  split_col: 'target'
  size_strategy: "even"
  min_samples: 50
  max_samples: 8000
  local_test_size: 0.1
  global_test_size: 0.1