name: 'niid-f2'
partition_params:
  partition_strategy: "niid_dir"
  split_col: 'feature'
  size_strategy: "even"
  min_samples: 50
  max_samples: 4000
  niid_alpha: 0.1
  local_test_size: 0.1
  global_test_size: 0.1
  reg_bins: 20