name: 'niid1'
partition_params:
  partition_strategy: "niid_dir"
  split_col: 'target'
  size_strategy: "even"
  min_samples: 100
  max_samples: 2000
  niid_alpha: 0.5
  local_test_size: 0.1
  global_test_size: 0.1