codrna:
  fed_strategy_client_params:
    mu: 0.01
california:
  fed_strategy_client_params:
    mu: 0.01
dvisits:
  fed_strategy_client_params:
    mu: 0.01
hhip:
  fed_strategy_client_params:
    mu: 0.01
hhip_np:
  fed_strategy_client_params:
    mu: 0.01
vehicle:
  fed_strategy_client_params:
    mu: 0.01
vehicle_np:
  fed_strategy_server_params:
    fine_tune_steps: 800
school:
  fed_strategy_client_params:
    mu: 0.01
school_np:
  fed_strategy_server_params:
    fine_tune_steps: 800