###########################################################################################
# CodRNA
codrna:
  imp_params:
    clip: true
    imp_model_params:
      latent_size: 8
      n_hidden: 32
      n_hidden_layers: 2
      out_dist: gaussian
      K: 20
      L: 500
      activation: tanh
      initializer: xavier
  model_train_params:
    initial_zero_impute: true
    global_epoch: 500
    local_epoch: 10
    batch_size: 512
    learning_rate: 0.001
    weight_decay: 0.0001
    use_early_stopping: true
    optimizer: adamw
    model_converge:
      tolerance: 0.003

###########################################################################################
# California
california:
  imp_params:
    clip: true
    imp_model_params:
      latent_size: 16
      n_hidden: 32
      n_hidden_layers: 2
      out_dist: gaussian
      K: 20
      L: 500
      activation: tanh
      initializer: xavier
  model_train_params:
    initial_zero_impute: true
    global_epoch: 400
    local_epoch: 5
    batch_size: 512
    learning_rate: 0.001
    weight_decay: 0.0001
    use_early_stopping: true
    optimizer: adamw
    model_converge:
      tolerance: 0.003

###########################################################################################
# Dvisits
dvisits:
  imp_params:
    clip: true
    imp_model_params:
      latent_size: 8
      n_hidden: 32
      n_hidden_layers: 2
      out_dist: gaussian
      K: 20
      L: 500
      activation: tanh
      initializer: xavier
  model_train_params:
    initial_zero_impute: true
    global_epoch: 500
    local_epoch: 10
    batch_size: 512
    learning_rate: 0.001
    weight_decay: 0.0001
    use_early_stopping: true
    optimizer: adamw
    model_converge:
      tolerance: 0.003

###########################################################################################
# HHIP
hhip:
  imp_params:
    clip: true
    imp_model_params:
      latent_size: 32
      n_hidden: 32
      n_hidden_layers: 2
      out_dist: gaussian
      K: 20
      L: 500
      activation: tanh
      initializer: xavier
  model_train_params:
    initial_zero_impute: false
    global_epoch: 500
    local_epoch: 10
    batch_size: 512
    learning_rate: 0.001
    weight_decay: 0.0001
    use_early_stopping: true
    optimizer: adamw
    model_converge:
      tolerance: 0.01

###########################################################################################
# Vehicle
vehicle:
  imp_params:
    clip: true
    imp_model_params:
      latent_size: 16
      n_hidden: 64
      n_hidden_layers: 2
      out_dist: gaussian
      K: 20
      L: 500
      activation: tanh
      initializer: xavier
  model_train_params:
    initial_zero_impute: true
    global_epoch: 300
    local_epoch: 5
    batch_size: 512
    learning_rate: 0.001
    weight_decay: 0.0001
    use_early_stopping: true
    optimizer: adamw
    model_converge:
      tolerance: 0.01

###########################################################################################
# School PCA
school_pca:
  imp_params:
    clip: true
    imp_model_params:
      latent_size: 16
      n_hidden: 32
      n_hidden_layers: 2
      out_dist: gaussian
      K: 20
      L: 500
      activation: tanh
      initializer: xavier
  model_train_params:
    initial_zero_impute: false
    global_epoch: 500
    local_epoch: 10
    batch_size: 512
    learning_rate: 0.001
    weight_decay: 0.0001
    use_early_stopping: true
    optimizer: adamw
    model_converge:
      tolerance: 0.01